version: '3.8'
services:
    es-pet-report:
        image: 'registry.cn-hangzhou.aliyuncs.com/redgreat/es-pet-report:latest'
        container_name: es-pet-report
        hostname: es-pet-report
        restart: unless-stopped
        ports:
            - 8080:8000
        volumes:
            - ./conf/:/app/conf
        environment:
            DISABLE_IPV6: 'true'
            TZ: 'Asia/Shanghai'
            LANG: 'zh_CN.UTF-8'
        deploy:
            resources:
                limits:
                    memory: 64M
                reservations:
                    memory: 8M
        mem_swappiness: 0
        oom_kill_disable: true
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
